apiVersion: oiw.dev/v1alpha1
kind: IntegrationProject
metadata:
  created: '2026-09-03T00:00:00Z'
  description: 'Integration project: XML to JSON Bridge'
  id: xml-json-bridge
  name: XML to JSON Bridge
spec:
  emg:
    confidentialityScope: project-private
    enabled: false
  minimumCompilerVersion: 0.1.0
  package: package/package.yaml
  secretProvider: local-keyring
  targetProfiles:
  - sap-cloud-integration-2026-07
